# Site settings
title: Levi Buzolic
email: levibuzolic@gmail.com
description: "Levi Buzolic - Software Developer, Designer, Photographer"
baseurl: ""
url: "http://levibuzolic.com"
twitter_username: levibuzolic
github_username: levibuzolic

# Build settings
markdown: kramdown
permalink: pretty
